'''
Problem 44:

Pentagonal numbers are generated by the formula, Pn = n(3*n-1)/2.  The first
ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145,...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.  However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
'''

def P(n):
    return int(n*(3*n-1)/2)


pentagonal_numbers = []
possible_sums = []

solution = False
n = 0
p_n = P(n)

while not solution:
    n += 1
    P_n = P(n)

    for possible_sum in possible_sums:
        if P_n == possible_sum[2]:
            print(f"solution: D = Pk({possible_sum[1]}) - Pj({possible_sum[0]}) = {possible_sum[1] - possible_sum[0]}")
            solution = True

    pentagonal_numbers += [P_n]

    for number in pentagonal_numbers:
        difference = P_n - number
        if difference in pentagonal_numbers:
            possible_sums += [(number, P_n, number + P_n)]
